executable = /user/sdansana/CMSSW_10_6_27/src/HToSS_analysis/JobTemplate.sh
arguments = $(cfg) $(output) $(flow) $(fhigh) $(dataset)

should_transfer_files = no

error = /user/sdansana/CMSSW_10_6_27/src/HToSS_analysis/error/error_$(dataset)_$(flow)-$(fhigh).txt
output = /user/sdansana/CMSSW_10_6_27/src/HToSS_analysis/out/out_$(dataset)_$(flow)-$(fhigh).txt
log = /user/sdansana/CMSSW_10_6_27/src/HToSS_analysis/log/log_$(dataset)_$(flow)-$(fhigh).txt

+JobFlavour = "microcentury"

queue cfg,output,flow,fhigh,dataset from params_fast.txt
