executable = /user/sdansana/CMSSW_10_6_27/src/HToSS_analysis/AnalyzeJob.sh
#executable = /user/sdansana/CMSSW_10_6_27/src/HToSS_analysis/WeightsJob.sh

arguments = $(cfg) $(cuts) $(output) $(flow) $(fhigh) $(dataset) $(year)

should_transfer_files = no

error = /user/sdansana/CMSSW_10_6_27/src/HToSS_analysis/error2/error_$(dataset)_$(flow)-$(fhigh).txt
output = /user/sdansana/CMSSW_10_6_27/src/HToSS_analysis/out2/out_$(dataset)_$(flow)-$(fhigh).txt
log = /user/sdansana/CMSSW_10_6_27/src/HToSS_analysis/log2/log_$(dataset)_$(flow)-$(fhigh).txt

#request_cpus=4
#request_memory=10000
+JobFlavour = "longlunch"
#+JobFlavour = "espresso"
queue cfg,cuts,output,flow,fhigh,dataset,year from params_signal_kaon_UL2018.txt 
