executable = /user/sdansana/CMSSW_10_6_27/src/HToSS_analysis/JobTemplateSkimmed.sh
arguments = $(cfg) $(cuts) $(output) $(flow) $(fhigh) $(dataset) $(weight)

should_transfer_files = no

error = /user/sdansana/CMSSW_10_6_27/src/HToSS_analysis/error/error_$(dataset)_$(flow)-$(fhigh).txt
output = /user/sdansana/CMSSW_10_6_27/src/HToSS_analysis/out/out_$(dataset)_$(flow)-$(fhigh).txt
log = /user/sdansana/CMSSW_10_6_27/src/HToSS_analysis/log/log_$(dataset)_$(flow)-$(fhigh).txt

+JobFlavour = "longlunch"

queue cfg,cuts,output,flow,fhigh,dataset,weight from params_skimmed_all.txt
