#./bin/quickKinematics.exe -c configs/2017/mumu_HtoSS_MS2_ctau0.yaml --2018 -u true -o plots/kinematicDistributions/postLepSkim_legacy/output_HtoSS_MS2_ctau0.root
#./bin/quickKinematics.exe -c configs/2017/mumu_HtoSS_MS2_ctau1.yaml --2018 -u true -o plots/kinematicDistributions/postLepSkim_legacy/output_HtoSS_MS2_ctau1.root
#./bin/quickKinematics.exe -c configs/2017/mumu_HtoSS_MS2_ctau10.yaml --2018 -u true -o plots/kinematicDistributions/postLepSkim_legacy/output_HtoSS_MS2_ctau10.root
#./bin/quickKinematics.exe -c configs/2017/mumu_HtoSS_MS2_ctau100.yaml --2018 -u true -o plots/kinematicDistributions/postLepSkim_legacy/output_HtoSS_MS2_ctau100.root
#for some reason, -u false doesn't work, default is false anyway
#should be able to run on other MC, eg, QCD
#./bin/quickIsoCustom.exe -c configs/2017/mumu_HtoSS_MS2_ctau0.yaml -o plots/IsoDistributions/output_HtoSS_MS2_ctau0.root --flow 1 --fhigh 5 -w plots/weightDistributions/output_HtoSS_MS2_ctau0.root 
#./bin/quickIsoCustom.exe -c configs/2017/mumu_HtoSS_MS2_ctau0.yaml -o plots/IsoDistributions/output_HtoSS_MS2_ctau0_new.root --flow 1 --fhigh 5
# GenPlotter
#./bin/quickGenPlotter.exe -c configs/2017/mumu_HtoSS_MS2_ctau0.yaml -o plots/genDistributions/output_HtoSS_MS2_ctau0.root --flow 1 --fhigh 5 -v true -n 500
#./bin/quickGenPlotter.exe -c configs/2017/mumu_HtoSS_MS2_ctau0.yaml -o plots/genDistributions/output_HtoSS_MS2_ctau0.root --flow 1 --fhigh 5
#./bin/quickWeightGenerator.exe -c configs/2017/mumu_HtoSS_MS2_ctau0.yaml -o plots/weightDistributions/output_HtoSS_MS2_ctau0.root --flow 1 --fhigh 5 --hack false
#./bin/quickIsoCustom.exe -c configs/2017/datasets/QCD/QCD_Pt-300to470_MuEnrichedPt5.yaml --cuts configs/2017/cuts/CRCuts_kaonmass.yaml -o plots/IsolationAndScalarMassCut/output_QCD_Pt-300to470_MuEnrichedPt5_1-5.root --flow 1 --fhigh 5 -w plots/weightDistributions/QCD/output_QCD_Pt-300to470_MuEnrichedPt5.root --hack true 

#./bin/quickIsoCustom.exe -c configs/2017/datasets/data/mumuRun2017F.yaml --cuts configs/2017/cuts/CRCuts_kaonmass.yaml -o plots/IsolationAndScalarMassCut/data/output_Run2017F.root --flow 1 --fhigh 5 --hack true 
#./bin/quickIsoCustom.exe -c configs/2017/datasets/data/mumuRun2017F.yaml --cuts configs/2017/cuts/CRCuts_kaonmass.yaml -o plots/IsolationAndScalarMassCut/data/output_Run2017F.root --flow 1 --fhigh 5 -w plots/weightDistributions/output_HtoSS_MS2_ctau0.root --hack true 
#./bin/quickIsoCustom_test.exe -c configs/2017/datasets/ggH/ggH_HToSS_MH125_MS2_ctauS0.yaml --cuts configs/2017/cuts/SRCuts_kaonmass.yaml -o plots/IsolationAndScalarMassCut/output_HtoSS_MS2_ctau0.root --flow 1 --fhigh 5 -w plots/weightDistributions/output_HtoSS_MS2_ctau0.root --hack true -n 1000 
./bin/quickIsoCustom.exe -c configs/2017/datasets/ggH/ggH_HToSS_MH125_MS2_ctauS0.yaml --cuts configs/2017/cuts/SRCuts_kaonmass.yaml -o plots/IsolationAndScalarMassCut_230626/output_HtoSS_MS2_ctau0.root --flow 1 --fhigh 5 -w plots/weightDistributions/output_HtoSS_MS2_ctau0.root --hack true 
#./bin/quickIsoCustom.exe -c configs/2017/datasets/ggH/ggH_HToSS_MH125_MS2_ctauS1.yaml --cuts configs/2017/cuts/SRCuts_kaonmass.yaml -o plots/IsolationAndScalarMassCut_230620/SR/output_HtoSS_MS2_ctau1.root --flow 1 --fhigh 6 -w plots/weightDistributions/output_HtoSS_MS2_ctau1.root --hack true 
#./bin/quickIsoCustom.exe -c configs/2017/datasets/ggH/ggH_HToSS_MH125_MS2_ctauS10.yaml --cuts configs/2017/cuts/SRCuts_kaonmass.yaml -o plots/IsolationAndScalarMassCut_230620/SR/output_HtoSS_MS2_ctau10.root --flow 1 --fhigh 9 -w plots/weightDistributions/output_HtoSS_MS2_ctau10.root --hack true 
#./bin/quickIsoCustom.exe -c configs/2017/datasets/ggH/ggH_HToSS_MH125_MS2_ctauS100.yaml --cuts configs/2017/cuts/SRCuts_kaonmass.yaml -o plots/IsolationAndScalarMassCut_230620/SR/output_HtoSS_MS2_ctau100.root --flow 1 --fhigh 20 -w plots/weightDistributions/output_HtoSS_MS2_ctau100.root --hack true 
#
#./bin/quickIsoCustom.exe -c configs/2017/datasets/ggH/ggH_HToSS_MH125_MS1p8_ctauS0.yaml --cuts configs/2017/cuts/SRCuts_kaonmass.yaml -o plots/IsolationAndScalarMassCut/SR/output_HtoSS_MS1p8_ctau0.root --flow 1 --fhigh 20 -w plots/weightDistributions/output_HtoSS_MS2_ctau0.root --hack true 
#./bin/quickIsoCustom.exe -c configs/2017/datasets/ggH/ggH_HToSS_MH125_MS1p6_ctauS0.yaml --cuts configs/2017/cuts/SRCuts_kaonmass.yaml -o plots/IsolationAndScalarMassCut/SR/output_HtoSS_MS1p6_ctau0.root --flow 1 --fhigh 20 -w plots/weightDistributions/output_HtoSS_MS2_ctau0.root --hack true 
#./bin/quickIsoCustom.exe -c configs/2017/datasets/ggH/ggH_HToSS_MH125_MS1p4_ctauS0.yaml --cuts configs/2017/cuts/SRCuts_kaonmass.yaml -o plots/IsolationAndScalarMassCut/SR/output_HtoSS_MS1p4_ctau0.root --flow 1 --fhigh 20 -w plots/weightDistributions/output_HtoSS_MS2_ctau0.root --hack true 
#./bin/quickIsoCustom.exe -c configs/2017/datasets/ggH/ggH_HToSS_MH125_MS1p2_ctauS0.yaml --cuts configs/2017/cuts/SRCuts_kaonmass.yaml -o plots/IsolationAndScalarMassCut/SR/output_HtoSS_MS1p2_ctau0.root --flow 1 --fhigh 20 -w plots/weightDistributions/output_HtoSS_MS2_ctau0.root --hack true 
#./bin/quickIsoCustom.exe -c configs/2017/datasets/ggH/ggH_HToSS_MH125_MS1p1_ctauS0.yaml --cuts configs/2017/cuts/SRCuts_kaonmass.yaml -o plots/IsolationAndScalarMassCut/SR/output_HtoSS_MS1p1_ctau0.root --flow 1 --fhigh 20 -w plots/weightDistributions/output_HtoSS_MS2_ctau0.root --hack true 
#./bin/quickIsoCustom.exe -c configs/2017/datasets/ggH/ggH_HToSS_MH125_MS1_ctauS0.yaml --cuts configs/2017/cuts/SRCuts_pionmass.yaml -o plots/IsolationAndScalarMassCut/SR/output_HtoSS_MS1_ctau0.root --flow 1 --fhigh 20 -w plots/weightDistributions/output_HtoSS_MS2_ctau0.root --hack true 
#./bin/quickIsoCustom.exe -c configs/2017/datasets/ggH/ggH_HToSS_MH125_MS0p9_ctauS0.yaml --cuts configs/2017/cuts/SRCuts_pionmass.yaml -o plots/IsolationAndScalarMassCut/SR/output_HtoSS_MS0p9_ctau0.root --flow 1 --fhigh 20 -w plots/weightDistributions/output_HtoSS_MS2_ctau0.root --hack true 
#./bin/quickIsoCustom.exe -c configs/2017/datasets/ggH/ggH_HToSS_MH125_MS0p8_ctauS0.yaml --cuts configs/2017/cuts/SRCuts_pionmass.yaml -o plots/IsolationAndScalarMassCut/SR/output_HtoSS_MS0p8_ctau0.root --flow 1 --fhigh 20 -w plots/weightDistributions/output_HtoSS_MS2_ctau0.root --hack true 
#./bin/quickIsoCustom.exe -c configs/2017/datasets/ggH/ggH_HToSS_MH125_MS0p6_ctauS0.yaml --cuts configs/2017/cuts/SRCuts_pionmass.yaml -o plots/IsolationAndScalarMassCut/SR/output_HtoSS_MS0p6_ctau0.root --flow 1 --fhigh 20 -w plots/weightDistributions/output_HtoSS_MS2_ctau0.root --hack true 
#./bin/quickIsoCustom.exe -c configs/2017/datasets/ggH/ggH_HToSS_MH125_MS0p4_ctauS0.yaml --cuts configs/2017/cuts/SRCuts_pionmass.yaml -o plots/IsolationAndScalarMassCut/SR/output_HtoSS_MS0p4_ctau0.root --flow 1 --fhigh 20 -w plots/weightDistributions/output_HtoSS_MS2_ctau0.root --hack true 
# ./bin/quickIsoCustom.exe -c configs/2017/datasets/ggH/ggH_HToSS_MH125_MS2_ctauS1.yaml -o plots/HiggsSideband/output_HtoSS_MS2_ctau1.root --flow 1 --fhigh 5 -w plots/weightDistributions/output_HtoSS_MS2_ctau1.root --hack true 
# ./bin/quickIsoCustom.exe -c configs/2017/datasets/ggH/ggH_HToSS_MH125_MS2_ctauS10.yaml -o plots/HiggsSideband/output_HtoSS_MS2_ctau10.root --flow 1 --fhigh 5 -w plots/weightDistributions/output_HtoSS_MS2_ctau10.root --hack true 
# ./bin/quickIsoCustom.exe -c configs/2017/datasets/ggH/ggH_HToSS_MH125_MS2_ctauS100.yaml -o plots/HiggsSideband/output_HtoSS_MS2_ctau100.root --flow 1 --fhigh 5 -w plots/weightDistributions/output_HtoSS_MS2_ctau100.root --hack true 
#./bin/quickIsoCustom_secondary.exe -c configs/2017/datasets/ggH/ggH_HToSS_MH125_MS1_ctauS0.yaml -o plots/IsoDistributions_new/output_HtoSS_MS1_ctau0.root --flow 1 --fhigh 1 -w "" --hack true 
#./bin/RDataFrames_test.exe -c configs/2017/datasets/ggH/ggH_HToSS_MH125_MS2_ctauS0.yaml -o plots/test_RDataFrames.root --flow 1 --fhigh 5 -w plots/weightDistributions/output_HtoSS_MS2_ctau0.root --hack true 
#./bin/quickIsoCustom.exe -c configs/2017/mumu_HtoSS_MS2_ctau0.yaml -o plots/IsoDistributions_new/output_HtoSS_MS2_ctau0.root --flow 1 --fhigh 5 -w plots/weightDistributions/output_HtoSS_MS2_ctau0.root --hack false
